version: '3.7'

services:

  nginx:
    ports:
      - "80:80"

  php:
    ports:
      - "2323:22"
#      - "9003:9003"
    # Allows to debug php script run inside PHP container
    environment:
      PHP_IDE_CONFIG: serverName=todop.loc

  mysql:
    ports:
      - "3306:3306"

  rmq:
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  db_data:
