doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_mysql
        charset: utf8mb4
        server_version: '8.0'
        types:
            uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
            datetime_immutable: App\Shared\Infrastructure\Persistence\Doctrine\Types\DateTimeType
            email: App\Shared\Infrastructure\Persistence\Doctrine\Types\EmailType
            hashed_password: App\Shared\Infrastructure\Persistence\Doctrine\Types\HashedPasswordType
            todolist_title: App\TodoList\Infrastructure\Persistence\Doctrine\Types\TodoListTitleType
        mapping_types:
            uuid_binary: binary
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/App/User/Domain'
                prefix: 'App\User'
                alias: AppUser
            TodoList:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/App/TodoList/Domain'
                prefix: 'App\TodoList'
                alias: AppTodoList