framework:
    messenger:
        failure_transport: failed
        default_bus: messenger.bus.command

        buses:
            messenger.bus.command:
                default_middleware: false
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
                    - handle_message
            messenger.bus.query:
              default_middleware: false
              middleware:
                - handle_message
            messenger.bus.event.async:
                default_middleware: allow_no_handlers

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            events:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    delay: 2000
                    max_retries: 5
                    multiplier: 2
                    max_delay: 0
                options:
                    exchange:
                        type: topic
                        name: events
                    queues:
                        events:
                            binding_keys: [ '#' ]
            sync: 'sync://'
            failed: 'sync://'


        routing:
            'App\Shared\Application\Command\CommandInterface': sync
            'App\Shared\Application\Query\QueryInterface': sync
            'App\Shared\Domain\Event\DomainEvent': events

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
