nelmio_api_doc:
    documentation:
        servers:
            - url: http://todop.loc
              description: API over HTTP
        info:
            title: TODOp
            description: TODO list for you!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            parameters:
                page:
                    name: page
                    in: query
                    example: 1
                    schema:
                        type: integer
                limit:
                    name: limit
                    in: query
                    example: 10
                    schema:
                        type: integer
            responses:
                users:
                    description: Users list
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        $ref: "#/components/schemas/User"
                                    relationships:
                                        $ref: "#/components/schemas/Relationships"

            schemas:
                User:
                    type: object
                    properties:
                        uuid:
                            type: string
                            example: 7be33fd4-ff46-11ea-adc1-0242ac120002
                        createdAt:
                            type: string
                            format: date-time
                        updatedAt:
                            type: string
                            format: date-time
                        credentials:
                            type: object
                            properties:
                                email:
                                    type: string
                                    example: 'j@j.com'
                                password:
                                    type: string
                                    example: ;klsdjhsd;gjkdhg;sldkgjhs;dlkgjsd;lfgkj
                ResponseCollectionMeta:
                    type: object
                    properties:
                        size:
                            type: integer
                        page:
                            type: integer
                        total:
                            type: integer
                Relationships:
                    type: object
                    properties:
                        data:
                            type: array
                            items:
                                type: object
                                properties:
                                    id:
                                        type: string
                                    type:
                                        type: string
                                    attributes:
                                        type: object
                Error:
                    type: object
                    properties:
                        error:
                            type: object
                            properties:
                                title:
                                    type: string
                                    example: InvalidArgumentException
                                detail:
                                    type: string
                                    example: 'Password should contain at least 6 characters'
                                code:
                                    type: string
                                    example: 500005322

        security:
            - Bearer: []

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
