version: '3.7'

services:

  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public:ro
    depends_on:
      - php

  php:
    build:
      dockerfile: docker/artifact/Dockerfile
      context: .
      target: php-dev
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
    # You can set the value of HOST_IP by the next command
    # make (start|stop) -e "HOST_IP=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')"
    extra_hosts:
      - "host.docker.internal:${HOST_IP}"
    volumes:
      - ./:/app:rw,delegated
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      - /app/var/
      - /app/var/cache/
      - /app/var/logs/
      - /app/var/sessions/
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./docker/dev/mysql:/etc/mysql/conf.d"
    tmpfs:
      - /var/lib/mysql/:rw,noexec,nosuid,size=600m
      - /tmp/:rw,noexec,nosuid,size=50m
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=api

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mysql
    command: mysql:3306

volumes:
  db-data:
